# Generated by Django 3.1 on 2020-08-23 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hint',
        ),
    ]
