# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-22 20:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='questions',
            field=models.ManyToManyField(blank=True, through='questions.QuestionTag', to='questions.Question'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='users', through='questions.UserTag', to=settings.AUTH_USER_MODEL),
        ),
    ]
