# Generated by Django 3.1 on 2020-08-23 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_delete_hint'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
