# Generated by Django 5.0.3 on 2024-06-28 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_remove_tag_users_delete_usertag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='querypreferences',
            name='is_default',
        ),
        migrations.AlterField(
            model_name='querypreferences',
            name='include_questions_with_answers',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='querypreferences',
            name='include_questions_without_answers',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='querypreferences',
            name='include_unanswered_questions',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='querypreferences',
            name='sort_by_oldest_answered_first',
            field=models.BooleanField(default=False),
        ),
    ]
