# Generated by Django 5.0.3 on 2024-09-16 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_remove_querypreferences_is_default_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QueryPreferences',
        ),
    ]
