# Generated by Django 5.0.3 on 2024-10-11 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_delete_querypreferences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questiontag',
            name='enabled',
        ),
    ]
