# Generated by Django 5.0.3 on 2024-10-20 06:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_remove_questiontag_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TagLineage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_added', models.DateTimeField(auto_now_add=True)),
                ('datetime_updated', models.DateTimeField(auto_now=True)),
                ('child_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='questions.tag')),
                ('parent_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='questions.tag')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'parent_tag', 'child_tag')},
            },
        ),
    ]
