version: '2'
services:
  db:
    image: postgres
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/opt/website
    ports:
      - "8000:8000"
    depends_on:
      - db
version: "3"
services:
  nginx_server:
    build:
        context: .
        dockerfile: Dockerfile-nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
        - django_server
    volumes:
      - ./conf.d:/etc/nginx/conf.d
  postgres:
     build:
        context: .
        dockerfile: Dockerfile-postgres
  django_server:
    build:
        context: .
        dockerfile: Dockerfile-web-server
    command: python -u -m http.server 80
    volumes:
      - ./web-root-1:/web-root
