[tool.poetry]
name = "quiz-me"
version = "0.1.0"
description = ""
authors = ["Rob Bednark <rbednark@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
asgiref = "3.3.1"
django = "3.1.4"
django-markdown-deux = "1.0.5"
django-pagedown = "2.2.0"
gunicorn = "20.0.4"
humanize = "3.2.0"
markdown2 = "2.3.10"
pillow = "8.0.1"
psycopg2 = "2.8.6"
py2-py3-django-email-as-username = "1.7.1"
pygments = "2.7.3"
python-dateutil = "2.8.1"
pytz = "2020.5"
six = "1.15.0"
sqlparse = "0.4.1"
urllib3 = "1.26.2"


[tool.poetry.group.dev.dependencies]
django-debug-toolbar = "3.2"
django-extensions = "3.1.0"
pudb = "2020.1"
selenium = "3.141.0"
splinter = "0.8.0"
urwid = "2.1.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
