[tool.poetry]
name = "quiz-me"
version = "0.1.0"
description = ""
authors = ["Rob Bednark <rbednark@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
asgiref = "3.3.*"
django = "3.1.*"
django-markdown-deux = "1.0.*"
django-pagedown = "2.2.*"
gunicorn = "20.0.*"
humanize = "3.2.*"
markdown2 = "2.3.*"
pillow = "8.0.*"
psycopg2 = "2.8.*"
py2-py3-django-email-as-username = "1.7.*"
pygments = "2.7.*"
python-dateutil = "2.8.*"
pytz = "2020.*"
six = "1.15.*"
sqlparse = "0.4.*"
urllib3 = "1.26.*"


[tool.poetry.group.dev.dependencies]
django-debug-toolbar = "3.2.*"
django-extensions = "3.1.*"
pudb = "2020.*"
selenium = "3.141.*"
splinter = "0.8.*"
urwid = "2.1.*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
